option(NEON_BUILD_SHARED_LIBS "Build Neon as shared library" ON)
if (${NEON_BUILD_SHARED_LIBS})
	message(STATUS "Building Neon as a shared library")
else ()
	message(STATUS "Building Neon as a static library")
endif ()